<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        \App\Models\User::factory()->create([
            'name' => 'Test User',
            'email' => 'admin@admin.com',
            'password' => Hash::make('Alfa512#'),
        ]);
        $foodCategories = [
            'Fruits',
            'Vegetables',
            'Meat and Poultry',
            'Seafood',
            'Dairy Products',
            'Grains and Cereals',
            'Baked Goods',
            'Desserts',
            'Beverages',
            'Snacks'
        ];

        foreach ($foodCategories as $foodCategory) {
            \App\Models\Category::factory()->create([
                'name' => $foodCategory,
            ]);
        }

        $menuItems = array(
            "Chicken Parmesan",
            "Margherita Pizza",
            "Grilled Salmon",
            "Caesar Salad",
            "Beef Burrito",
            "Mushroom Risotto",
            "Fish and Chips",
            "Spinach and Feta Stuffed Chicken",
            "Cheeseburger",
            "Vegetable Stir-Fry",
            "Penne Alfredo",
            "Hawaiian Pizza",
            "BBQ Ribs",
            "Greek Salad",
            "Shrimp Scampi",
            "Taco Salad",
            "Chicken Fried Rice",
            "New York Strip Steak",
            "Caprese Panini",
            "Vegetable Curry",
            "Lobster Bisque",
            "Chicken Shawarma",
            "Cobb Salad",
            "Sushi Platter",
            "Beef Tacos",
            "Pesto Pasta",
            "Fajitas",
            "Eggplant Parmesan",
            "Cheese Ravioli",
            "Miso Soup",
            "Chicken Quesadilla",
            "Mediterranean Salad",
            "Fish Tacos",
            "Lemon Herb Roasted Chicken",
            "Club Sandwich",
            "Pad Thai",
            "Beef Stir-Fry",
            "Vegetarian Pizza",
            "Grilled Shrimp Skewers",
            "Chicken and Waffles",
            "Spaghetti Bolognese",
            "Veggie Burger",
            "Chicken Caesar Wrap",
            "Sushi Roll Combo",
            "Chili Cheese Fries",
            "Chicken Tikka Masala",
            "Caprese Salad",
            "Crab Cakes",
            "Tofu Stir-Fry",
            "Pepperoni Pizza",
            "Steak Sandwich",
            "Veggie Burrito",
            "Baked Ziti",
            "Clam Chowder",
            "Gyro",
            "Fettuccine Alfredo",
            "Shrimp Pad Thai",
            "BBQ Chicken Pizza",
            "Beef and Broccoli",
            "Portobello Mushroom Burger",
            "Chicken Satay",
            "Fried Calamari",
            "Greek Gyro Wrap",
            "Vegetable Lasagna",
            "Tomato Basil Soup",
            "Beef Enchiladas",
            "Butter Chicken",
            "Cajun Shrimp Pasta",
            "Egg Fried Rice",
            "Margherita Panini",
            "Chicken Tacos",
            "Pasta Primavera",
            "Veggie Stir-Fry",
            "Pho",
            "Cheese Fries",
            "Veggie Wrap",
            "Szechuan Beef",
            "Mediterranean Pizza",
            "Crab Rangoon",
            "Vegetable Biryani",
            "Chicken Marsala",
            "Avocado Salad",
            "Lobster Roll",
            "Vegetable Tempura",
            "Garden Burger",
            "Chicken and Broccoli",
            "Teriyaki Salmon",
            "Vegetable Curry",
            "Margherita Pizza",
            "Spicy Tuna Roll",
            "Chicken Fried Rice",
            "Cheeseburger",
            "Penne Alfredo",
            "Hawaiian Pizza",
            "BBQ Ribs",
            "Greek Salad",
            "Shrimp Scampi",
            "Taco Salad",
            "Chicken Fried Rice",
            "New York Strip Steak",
            "Caprese Panini",
            "Vegetable Curry",
            "Lobster Bisque",
            "Chicken Shawarma",
            "Cobb Salad",
            "Sushi Platter",
            "Beef Tacos",
            "Pesto Pasta",
            "Fajitas",
            "Eggplant Parmesan",
            "Cheese Ravioli",
            "Miso Soup",
            "Chicken Quesadilla",
            "Mediterranean Salad",
            "Fish Tacos",
            "Lemon Herb Roasted Chicken",
            "Club Sandwich",
            "Pad Thai",
            "Beef Stir-Fry",
            "Vegetarian Pizza",
            "Grilled Shrimp Skewers",
            "Chicken and Waffles",
            "Spaghetti Bolognese",
            "Veggie Burger",
            "Chicken Caesar Wrap",
            "Sushi Roll Combo",
            "Chili Cheese Fries",
            "Chicken Tikka Masala",
            "Caprese Salad",
            "Crab Cakes",
            "Tofu Stir-Fry",
            "Pepperoni Pizza",
            "Steak Sandwich",
            "Veggie Burrito",
            "Baked Ziti",
            "Clam Chowder",
            "Gyro",
            "Fettuccine Alfredo",
            "Shrimp Pad Thai",
            "BBQ Chicken Pizza",
            "Beef and Broccoli",
            "Portobello Mushroom Burger",
            "Chicken Satay",
            "Fried Calamari",
            "Greek Gyro Wrap",
            "Vegetable Lasagna",
            "Tomato Basil Soup",
            "Beef Enchiladas",
            "Butter Chicken",
            "Cajun Shrimp Pasta",
            "Egg Fried Rice",
            "Margherita Panini",
            "Chicken Tacos",
            "Pasta Primavera",
            "Veggie Stir-Fry",
            "Pho",
            "Cheese Fries",
            "Veggie Wrap",
            "Szechuan Beef",
            "Mediterranean Pizza",
            "Crab Rangoon",
            "Vegetable Biryani",
            "Chicken Marsala",
            "Avocado Salad",
            "Lobster Roll",
            "Vegetable Tempura",
            "Garden Burger",
            "Chicken and Broccoli",
            "Teriyaki Salmon"
        );


        foreach ($menuItems as $key => $value) {
            \App\Models\Product::factory()->create([
                'name' => $value,
                'price' => rand(10, 100),
            ]);
        }
    }
}
